---
name: macOS check
on:
  push:
    branches:
      - bgworker-tasks-kqueue
      - bgworker-tasks-macref
permissions:
  contents: read
env:
  GOTOOLCHAIN: local
  GOFLAGS: "-tags=nowatcher,nobadger,nomysql,nopgx"
jobs:
  tests-mac:
    name: Tests (macOS, PHP 8.5)
    runs-on: macos-latest
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/setup-php
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Set CGO flags
        run: |
          {
           echo "CGO_CFLAGS=-I/opt/homebrew/include/ -DFRANKENPHP_TEST $(php-config --includes)"
           echo "CGO_LDFLAGS=-L/opt/homebrew/lib/ $(php-config --ldflags) $(php-config --libs)"
          } >> "${GITHUB_ENV}"
      - name: Build
        run: go build -tags nowatcher
      - name: Run library tests
        run: gotestsum -- -tags nowatcher -race ./...
